export const CATEGORIES = {
  privacy_security: "Privacy & Security",
  network: "Network",
  setup_backup_restore: "Setup/Backup/Restore",
  apple_account_icloud: "Apple Account & iCloud",
};

export const QUESTIONS = [
  // Privacy & Security
  {
    id: "ps-1",
    category: "privacy_security",
    difficulty: 1,
    question: "A user wants to stop apps from tracking them across other companies’ apps and websites. What should you check first on iPhone?",
    choices: [
      "Settings > Privacy & Security > Tracking",
      "Settings > Safari > Block Pop-ups",
      "Settings > Face ID & Passcode > Require Passcode",
      "Settings > General > VPN & Device Management",
    ],
    answerIndex: 0,
    explanation: "App Tracking Transparency is managed under Privacy & Security > Tracking.",
  },
  {
    id: "ps-2",
    category: "privacy_security",
    difficulty: 2,
    question: "Which feature most directly protects data on a lost iPhone by encrypting storage tied to the passcode?",
    choices: [
      "Low Power Mode",
      "Find My (Activation Lock)",
      "Data Protection (encryption with passcode)",
      "Background App Refresh",
    ],
    answerIndex: 2,
    explanation: "Encryption that depends on the passcode is the core protection for data at rest.",
  },
  {
    id: "ps-3",
    category: "privacy_security",
    difficulty: 2,
    question: "A Mac user says they keep getting prompts that a system extension was blocked. Where do you typically allow it (if it’s trusted)?",
    choices: [
      "System Settings > Privacy & Security",
      "Finder > Preferences",
      "Terminal > sudo allow-extension",
      "Keychain Access > System Roots",
    ],
    answerIndex: 0,
    explanation: "On modern macOS, approvals commonly appear in Privacy & Security.",
  },
  {
    id: "ps-4",
    category: "privacy_security",
    difficulty: 3,
    question: "Which is the best first step if a user suspects their Apple Account is compromised?",
    choices: [
      "Turn off Wi-Fi forever",
      "Change Apple Account password and review trusted devices",
      "Erase the device immediately without checking anything",
      "Disable notifications",
    ],
    answerIndex: 1,
    explanation: "Reset credentials and review trusted devices/sessions before going nuclear.",
  },
  {
    id: "ps-5",
    category: "privacy_security",
    difficulty: 2,
    question: "A user asks what a VPN does. What is the most accurate simple answer?",
    choices: [
      "It makes you anonymous to everyone everywhere",
      "It encrypts traffic between your device and the VPN server, and routes through that server",
      "It deletes your browsing history automatically",
      "It blocks all malware",
    ],
    answerIndex: 1,
    explanation: "VPNs encrypt the tunnel to the VPN endpoint and change routing, not reality.",
  },

  // Network
  {
    id: "net-1",
    category: "network",
    difficulty: 1,
    question: "If an iPhone shows Wi-Fi connected but no internet, what’s a good first check?",
    choices: [
      "Try another website/app and check if cellular data works",
      "Erase all content and settings",
      "Replace the router immediately",
      "Disable Bluetooth",
    ],
    answerIndex: 0,
    explanation: "Confirm whether it’s the network path or just one service/app.",
  },
  {
    id: "net-2",
    category: "network",
    difficulty: 2,
    question: "A Mac can’t resolve any website names, but can ping an IP address. What’s likely wrong?",
    choices: [
      "Display brightness",
      "DNS configuration",
      "Keyboard layout",
      "Battery health",
    ],
    answerIndex: 1,
    explanation: "IP works but names don’t implies name resolution (DNS) issues.",
  },
  {
    id: "net-3",
    category: "network",
    difficulty: 2,
    question: "What does forgetting a Wi-Fi network on iPhone do?",
    choices: [
      "Deletes the router firmware",
      "Removes the saved network and credentials so you can rejoin fresh",
      "Disables Wi-Fi permanently",
      "Erases the phone",
    ],
    answerIndex: 1,
    explanation: "It removes saved settings for that SSID, useful for credential/config issues.",
  },
  {
    id: "net-4",
    category: "network",
    difficulty: 3,
    question: "A user is on public Wi-Fi and wants to reduce exposure. Which is a practical recommendation?",
    choices: [
      "Use HTTPS sites/apps and consider a trusted VPN; disable auto-join for public networks",
      "Turn the screen off when not looking at it",
      "Change wallpaper",
      "Use airplane mode while browsing",
    ],
    answerIndex: 0,
    explanation: "Minimize risky auto-joins; encrypt traffic; prefer secure protocols.",
  },

  // Setup / Backup / Restore
  {
    id: "sbr-1",
    category: "setup_backup_restore",
    difficulty: 1,
    question: "During iPhone setup, what’s the main benefit of Quick Start?",
    choices: [
      "It disables Activation Lock",
      "It transfers settings/data from a nearby device using a guided flow",
      "It updates iOS without Wi-Fi",
      "It replaces iCloud",
    ],
    answerIndex: 1,
    explanation: "Quick Start speeds setup and transfers many settings and data.",
  },
  {
    id: "sbr-2",
    category: "setup_backup_restore",
    difficulty: 2,
    question: "A user wants the most complete local backup of an iPhone to a computer. What should you suggest?",
    choices: [
      "A standard backup without encryption",
      "An encrypted computer backup",
      "Only iCloud Photos",
      "Only syncing music",
    ],
    answerIndex: 1,
    explanation: "Encrypted computer backups can include more sensitive data than non-encrypted.",
  },
  {
    id: "sbr-3",
    category: "setup_backup_restore",
    difficulty: 2,
    question: "A restore failed with a generic error. What is a reasonable early troubleshooting step?",
    choices: [
      "Try a different cable/port and update the computer software, then retry",
      "Throw the device in rice",
      "Disable all security updates",
      "Rename the device",
    ],
    answerIndex: 0,
    explanation: "Connections and software versions cause a shocking amount of problems.",
  },
  {
    id: "sbr-4",
    category: "setup_backup_restore",
    difficulty: 3,
    question: "What’s the safest order when a user wants to erase their iPhone before selling it?",
    choices: [
      "Erase first, then sign out later",
      "Sign out of Apple Account/Find My, then erase all content and settings",
      "Remove SIM only, done",
      "Just delete photos",
    ],
    answerIndex: 1,
    explanation: "Sign out / disable Find My to avoid locking the next owner out.",
  },

  // Apple Account & iCloud
  {
    id: "ic-1",
    category: "apple_account_icloud",
    difficulty: 1,
    question: "What is iCloud primarily used for on Apple devices?",
    choices: [
      "Only email",
      "Syncing and storing data across devices and enabling services like backups",
      "Replacing Wi-Fi",
      "Increasing battery life",
    ],
    answerIndex: 1,
    explanation: "It’s for sync/storage plus Apple services that rely on the account.",
  },
  {
    id: "ic-2",
    category: "apple_account_icloud",
    difficulty: 2,
    question: "A user forgot their Apple Account password. What’s the correct direction?",
    choices: [
      "Tell them to guess until it works",
      "Use Apple’s account recovery / password reset flow",
      "Create a new Apple Account and ignore the old one",
      "Disable passcode and retry",
    ],
    answerIndex: 1,
    explanation: "Use official recovery/reset. Creating a new account causes more pain later.",
  },
  {
    id: "ic-3",
    category: "apple_account_icloud",
    difficulty: 2,
    question: "What does Activation Lock help prevent?",
    choices: [
      "Screen scratches",
      "Unauthorized reactivation of a device tied to an Apple Account",
      "Low storage",
      "Slow Wi-Fi",
    ],
    answerIndex: 1,
    explanation: "Activation Lock ties the device to the Apple Account (via Find My).",
  },
  {
    id: "ic-4",
    category: "apple_account_icloud",
    difficulty: 3,
    question: "A user’s iCloud storage is full and backups stopped. What’s the most practical fix?",
    choices: [
      "Turn the phone off",
      "Buy more iCloud storage or reduce what’s being backed up (photos/backups/apps)",
      "Disable passcode",
      "Reset network settings",
    ],
    answerIndex: 1,
    explanation: "Either increase storage or reduce usage. Magic is not included.",
  },

  // Extra pool to support larger exams
  {
    id: "ps-6",
    category: "privacy_security",
    difficulty: 1,
    question: "Which setting controls whether Location Services are enabled system-wide on iPhone?",
    choices: [
      "Settings > Privacy & Security > Location Services",
      "Settings > Sounds & Haptics",
      "Settings > Display & Brightness",
      "Settings > Wallet & Apple Pay",
    ],
    answerIndex: 0,
    explanation: "Location Services lives in Privacy & Security.",
  },
  {
    id: "net-5",
    category: "network",
    difficulty: 3,
    question: "A user can browse on Wi-Fi but some apps fail on a corporate network. What’s a likely cause?",
    choices: [
      "Firewall/proxy restrictions affecting specific services",
      "Battery percentage too low",
      "Font size too big",
      "AirDrop is off",
    ],
    answerIndex: 0,
    explanation: "Enterprise networks often filter ports/domains or require proxy settings.",
  },
  {
    id: "sbr-5",
    category: "setup_backup_restore",
    difficulty: 1,
    question: "If a user wants to transfer to a new iPhone with minimal hassle, what’s a good default suggestion?",
    choices: [
      "Quick Start or restore from recent backup",
      "Reinstall every app manually and hope",
      "Only copy photos",
      "Use a third-party cleaner app",
    ],
    answerIndex: 0,
    explanation: "Quick Start or backup restore is the standard path.",
  },
  {
    id: "ic-5",
    category: "apple_account_icloud",
    difficulty: 3,
    question: "A user sees prompts for an old Apple Account on a device they used to own. What’s a reasonable first step?",
    choices: [
      "Sign out of the old account on that device and sign in with the correct one",
      "Ignore it forever",
      "Erase the router",
      "Change the device language",
    ],
    answerIndex: 0,
    explanation: "Old account prompts usually mean the device is still signed into something.",
  },
];
